# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0069_unit_extensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicenode',
            options={'ordering': ['name']},
        ),
    ]
